language: php

php:
- 7.0
- hhvm

matrix:
  allow_failures:
  - php: 7.0
  include:
    env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

cache:
  directories:
  - $HOME/.composer/cache

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
- ./vendor/bin/phpunit -c phpunit.xml tests/ --coverage-clover=coverage.clover

after_script:
- php ./vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

after_success:
- wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
- php php-coveralls.phar --verbose;